export default {
  CREATE_MEAL: 'CREATE_MEAL',
  CREATE_MEAL_REQUEST: 'CREATE_MEAL_REQUEST',
  CREATE_MEAL_SUCCESS: 'CREATE_MEAL_SUCCESS',
  CREATE_MEAL_FAILURE: 'CREATE_MEAL_FAILURE',

  REMOVE_MEAL: 'REMOVE_MEAL',
  REMOVE_MEAL_REQUEST: 'REMOVE_MEAL_REQUEST',
  REMOVE_MEAL_SUCCESS: 'REMOVE_MEAL_SUCCESS',
  REMOVE_MEAL_FAILURE: 'REMOVE_MEAL_FAILURE',

  GET_MY_MEALS: 'GET_MY_MEALS',
  GET_MY_MEALS_REQUEST: 'GET_MY_MEALS_REQUEST',
  GET_MY_MEALS_SUCCESS: 'GET_MY_MEALS_SUCCESS',
  GET_MY_MEALS_FAILURE: 'GET_MY_MEALS_FAILURE',

  WRITE_REVIEW_MEAL: 'WRITE_REVIEW_MEAL',
  WRITE_REVIEW_MEAL_REQUEST: 'WRITE_REVIEW_MEAL_REQUEST',
  WRITE_REVIEW_MEAL_SUCCESS: 'WRITE_REVIEW_MEAL_SUCCESS',
  WRITE_REVIEW_MEAL_FAILURE: 'WRITE_REVIEW_MEAL_FAILURE',

  GET_MEAL: 'GET_MEAL',
  GET_MEAL_REQUEST: 'GET_MEAL_REQUEST',
  GET_MEAL_SUCCESS: 'GET_MEAL_SUCCESS',
  GET_MEAL_FAILURE: 'GET_MEAL_FAILURE',

  RESET_MEAL: 'RESET_MEAL',
};
