export default {
  CREATE_ORDER: 'CREATE_ORDER',
  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

  GET_MY_ORDERS: 'GET_MY_ORDERS',
  GET_MY_ORDERS_REQUEST: 'GET_MY_ORDERS_REQUEST',
  GET_MY_ORDERS_SUCCESS: 'GET_MY_ORDERS_SUCCESS',
  GET_MY_ORDERS_FAILURE: 'GET_MY_ORDERS_FAILURE',

  GET_ORDER: 'GET_ORDER',
  GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

  GET_NEARBY_ORDERS: 'GET_NEARBY_ORDERS',
  GET_NEARBY_ORDERS_REQUEST: 'GET_NEARBY_ORDERS_REQUEST',
  GET_NEARBY_ORDERS_SUCCESS: 'GET_NEARBY_ORDERS_SUCCESS',
  GET_NEARBY_ORDERS_FAILURE: 'GET_NEARBY_ORDERS_FAILURE',

  PICKUP_ORDER: 'PICKUP_ORDER',
  PICKUP_ORDER_REQUEST: 'PICKUP_ORDER_REQUEST',
  PICKUP_ORDER_SUCCESS: 'PICKUP_ORDER_SUCCESS',
  PICKUP_ORDER_FAILURE: 'PICKUP_ORDER_FAILURE',

  COMPLETE_ORDER: 'COMPLETE_ORDER',
  COMPLETE_ORDER_REQUEST: 'COMPLETE_ORDER_REQUEST',
  COMPLETE_ORDER_SUCCESS: 'COMPLETE_ORDER_SUCCESS',
  COMPLETE_ORDER_FAILURE: 'COMPLETE_ORDER_FAILURE',

  RESET_ORDER: 'RESET_ORDER',
};
  