export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  RESTORE_USER: 'RESTORE_USER',
  RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
  RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
  RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',

  REGISTER_CUSTOMER: 'REGISTER_CUSTOMER',
  REGISTER_CUSTOMER_REQUEST: 'REGISTER_CUSTOMER_REQUEST',
  REGISTER_CUSTOMER_SUCCESS: 'REGISTER_CUSTOMER_SUCCESS',
  REGISTER_CUSTOMER_FAILURE: 'REGISTER_CUSTOMER_FAILURE',

  REGISTER_CHEF: 'REGISTER_CHEF',
  REGISTER_CHEF_REQUEST: 'REGISTER_CHEF_REQUEST',
  REGISTER_CHEF_SUCCESS: 'REGISTER_CHEF_SUCCESS',
  REGISTER_CHEF_FAILURE: 'REGISTER_CHEF_FAILURE',

  NEARBY_CHEFS: 'NEARBY_CHEFS',
  NEARBY_CHEFS_REQUEST: 'NEARBY_CHEFS_REQUEST',
  NEARBY_CHEFS_SUCCESS: 'NEARBY_CHEFS_SUCCESS',
  NEARBY_CHEFS_FAILURE: 'NEARBY_CHEFS_FAILURE',

  WRITE_REVIEW_USER: 'WRITE_REVIEW_USER',
  WRITE_REVIEW_USER_REQUEST: 'WRITE_REVIEW_USER_REQUEST',
  WRITE_REVIEW_USER_SUCCESS: 'WRITE_REVIEW_USER_SUCCESS',
  WRITE_REVIEW_USER_FAILURE: 'WRITE_REVIEW_USER_FAILURE',

  ADD_SHIPPING_ADDRESS: 'ADD_SHIPPING_ADDRESS',
  ADD_SHIPPING_ADDRESS_REQUEST: 'ADD_SHIPPING_ADDRESS_REQUEST',
  ADD_SHIPPING_ADDRESS_SUCCESS: 'ADD_SHIPPING_ADDRESS_SUCCESS',
  ADD_SHIPPING_ADDRESS_FAILURE: 'ADD_SHIPPING_ADDRESS_FAILURE',

  EDIT_SHIPPING_ADDRESS: 'EDIT_SHIPPING_ADDRESS',
  EDIT_SHIPPING_ADDRESS_REQUEST: 'EDIT_SHIPPING_ADDRESS_REQUEST',
  EDIT_SHIPPING_ADDRESS_SUCCESS: 'EDIT_SHIPPING_ADDRESS_SUCCESS',
  EDIT_SHIPPING_ADDRESS_FAILURE: 'EDIT_SHIPPING_ADDRESS_FAILURE',

  REMOVE_SHIPPING_ADDRESS: 'REMOVE_SHIPPING_ADDRESS',
  REMOVE_SHIPPING_ADDRESS_REQUEST: 'REMOVE_SHIPPING_ADDRESS_REQUEST',
  REMOVE_SHIPPING_ADDRESS_SUCCESS: 'REMOVE_SHIPPING_ADDRESS_SUCCESS',
  REMOVE_SHIPPING_ADDRESS_FAILURE: 'REMOVE_SHIPPING_ADDRESS_FAILURE',

  CHANGE_ACTIVE_SHIPPING_ADDRESS: 'CHANGE_ACTIVE_SHIPPING_ADDRESS',
  CHANGE_ACTIVE_SHIPPING_ADDRESS_REQUEST: 'CHANGE_ACTIVE_SHIPPING_ADDRESS_REQUEST',
  CHANGE_ACTIVE_SHIPPING_ADDRESS_SUCCESS: 'CHANGE_ACTIVE_SHIPPING_ADDRESS_SUCCESS',
  CHANGE_ACTIVE_SHIPPING_ADDRESS_FAILURE: 'CHANGE_ACTIVE_SHIPPING_ADDRESS_FAILURE',

  ADD_PAYMENT: 'ADD_PAYMENT',
  ADD_PAYMENT_REQUEST: 'ADD_PAYMENT_REQUEST',
  ADD_PAYMENT_SUCCESS: 'ADD_PAYMENT_SUCCESS',
  ADD_PAYMENT_FAILURE: 'ADD_PAYMENT_FAILURE',

  EDIT_PAYMENT: 'EDIT_PAYMENT',
  EDIT_PAYMENT_REQUEST: 'EDIT_PAYMENT_REQUEST',
  EDIT_PAYMENT_SUCCESS: 'EDIT_PAYMENT_SUCCESS',
  EDIT_PAYMENT_FAILURE: 'EDIT_PAYMENT_FAILURE',

  REMOVE_PAYMENT: 'REMOVE_PAYMENT',
  REMOVE_PAYMENT_REQUEST: 'REMOVE_PAYMENT_REQUEST',
  REMOVE_PAYMENT_SUCCESS: 'REMOVE_PAYMENT_SUCCESS',
  REMOVE_PAYMENT_FAILURE: 'REMOVE_PAYMENT_FAILURE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VERIFY_CODE_PASSWORD: 'VERIFY_CODE_PASSWORD',
  VERIFY_CODE_PASSWORD_REQUEST: 'VERIFY_CODE_PASSWORD_REQUEST',
  VERIFY_CODE_PASSWORD_SUCCESS: 'VERIFY_CODE_PASSWORD_SUCCESS',
  VERIFY_CODE_PASSWORD_FAILURE: 'VERIFY_CODE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_CHEF: 'GET_CHEF',
  GET_CHEF_REQUEST: 'GET_CHEF_REQUEST',
  GET_CHEF_SUCCESS: 'GET_CHEF_SUCCESS',
  GET_CHEF_FAILURE: 'GET_CHEF_FAILURE',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_REQUEST: 'CHECK_EMAIL_REQUEST',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',

  WITHDRAW_WITH_PAYPAL: 'WITHDRAW_WITH_PAYPAL',
  WITHDRAW_WITH_PAYPAL_REQUEST: 'WITHDRAW_WITH_PAYPAL_REQUEST',
  WITHDRAW_WITH_PAYPAL_SUCCESS: 'WITHDRAW_WITH_PAYPAL_SUCCESS',
  WITHDRAW_WITH_PAYPAL_FAILURE: 'WITHDRAW_WITH_PAYPAL_FAILURE',

  WITHDRAW_WITH_BANK: 'WITHDRAW_WITH_BANK',
  WITHDRAW_WITH_BANK_REQUEST: 'WITHDRAW_WITH_BANK_REQUEST',
  WITHDRAW_WITH_BANK_SUCCESS: 'WITHDRAW_WITH_BANK_SUCCESS',
  WITHDRAW_WITH_BANK_FAILURE: 'WITHDRAW_WITH_BANK_FAILURE',
  
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_PLAYER_ID: 'SET_PLAYER_ID',
  SET_GEO_LOCATION: 'SET_GEO_LOCATION',
  SET_ZIPCODE: 'SET_ZIPCODE',
  SET_CART_BADGE: 'SET_CART_BADGE',
  UPDATE_NEARBY_MEAL: 'UPDATE_NEARBY_MEAL',
  RESET_USER: 'RESET_USER',
};
