const Images = {
    main_bg: require('../../assets/images/main_bg.png'),
	main_logo: require('../../assets/images/main_logo.png'),
    btn_google_plus: require('../../assets/images/btn_google_plus.png'),
    btn_facebook: require('../../assets/images/btn_facebook.png'),
    home_top_bar: require('../../assets/images/home_top_bar.png'),
    type_customer: require('../../assets/images/type_customer.png'),
    type_customer_selected: require('../../assets/images/type_customer_selected.png'),
    type_chef: require('../../assets/images/type_chef.png'),
    type_chef_selected: require('../../assets/images/type_chef_selected.png'),
    upload_photo_icon: require('../../assets/images/upload_photo_icon.png'),
    top_bg: require('../../assets/images/top_bg.png'),
    circle_plus_icon: require('../../assets/images/circle_plus_icon.png'),
    circle_minus: require('../../assets/images/circle_minus.png'),
    icon_direction: require('../../assets/images/icon_direction.png'),
    forward_arrow: require('../../assets/images/forward_arrow.png'),
    icon_menu_pin: require('../../assets/images/icon_menu_pin.png'),
    icon_chef: require('../../assets/images/icon_chef.png'),
    icon_time: require('../../assets/images/icon_time.png'),
    icon_customer: require('../../assets/images/icon_customer.png'),
    icon_withdrawal: require('../../assets/images/icon_withdrawal.png'),
    paypal: require('../../assets/images/paypal.png'),
    credit_card: require('../../assets/images/credit_card.png'),

    tab_home_active: require('../../assets/images/tab_home_active.png'),
    tab_home_inactive: require('../../assets/images/tab_home_inactive.png'),
    tab_menu_active: require('../../assets/images/tab_menu_active.png'),
    tab_menu_inactive: require('../../assets/images/tab_menu_inactive.png'),
    tab_notification_active: require('../../assets/images/tab_notification_active.png'),
    tab_notification_inactive: require('../../assets/images/tab_notification_inactive.png'),
    tab_order_active: require('../../assets/images/tab_order_active.png'),
    tab_order_inactive: require('../../assets/images/tab_order_inactive.png'),
    tab_profile_active: require('../../assets/images/tab_profile_active.png'),
    tab_profile_inactive: require('../../assets/images/tab_profile_inactive.png'),
    tab_add: require('../../assets/images/tab_add.png'),

    id_card_icon: require('../../assets/images/id_card_icon.png'),
    product_placeholder: require('../../assets/images/product_placeholder.png'),
    icon_cart: require('../../assets/images/icon_cart.png'),
    icon_cart_selected: require('../../assets/images/icon_cart_selected.png'),
    icon_circle_minus: require('../../assets/images/icon_circle_minus.png'),
    icon_circle_plus: require('../../assets/images/icon_circle_plus.png'),
    icon_profile: require('../../assets/images/icon_profile.png'),
    icon_manage_orders: require('../../assets/images/icon_manage_orders.png'),
    icon_password: require('../../assets/images/icon_password.png'),
    icon_tos: require('../../assets/images/icon_tos.png'),
    icon_privacy_policy: require('../../assets/images/icon_privacy_policy.png'),
    icon_link: require('../../assets/images/icon_link.png'),
    icon_phone: require('../../assets/images/icon_phone.png'),
    icon_email: require('../../assets/images/icon_email.png'),
    qty_minus: require('../../assets/images/qty_minus.png'),
    qty_plus: require('../../assets/images/qty_plus.png'),
    icon_trash: require('../../assets/images/icon_trash.png'),
    icon_trash_white: require('../../assets/images/icon_trash_white.png'),
    icon_shop: require('../../assets/images/icon_shop.png'),
    icon_pin: require('../../assets/images/icon_pin.png'),
    icon_payments: require('../../assets/images/icon_payments.png'),
    thankyou_smile: require('../../assets/images/thankyou_smile.png'),
    empty_cart: require('../../assets/images/empty_cart.png'),

    email_icon: require('../../assets/images/email_icon.png'),
    password_icon: require('../../assets/images/password_icon.png'),
    checkbox_selected: require('../../assets/images/checkbox_selected.png'),
    checkbox_normal: require('../../assets/images/checkbox_normal.png'),
    eye_icon: require('../../assets/images/eye_icon.png'),
    eye_hide_icon: require('../../assets/images/eye_hide_icon.png'),
    back_arrow: require('../../assets/images/back_arrow.png'),
    back_arrow_white: require('../../assets/images/back_arrow_white.png'),
    dropdown_icon: require('../../assets/images/dropdown_icon.png'),
    photo_icon: require('../../assets/images/photo_icon.png'),
    red_close_button: require('../../assets/images/red_close_button.png'),
    account_icon: require('../../assets/images/account_icon.png'),
    tick_white: require('../../assets/images/tick_white.png'),    
    close_icon: require('../../assets/images/close_icon.png'),        
    sad: require('../../assets/images/sad.png'),        
    notification_icon: require('../../assets/images/notification_icon.png'),        
    search_icon: require('../../assets/images/search_icon.png'),
    search_icon_white: require('../../assets/images/search_icon_white.png'),
    search_icon_black: require('../../assets/images/search_icon_black.png'),
    arrow_right: require('../../assets/images/arrow_right.png'),    
    star_selected: require('../../assets/images/star_selected.png'),    
    star_icon: require('../../assets/images/star_icon.png'),    
    icon_menu: require('../../assets/images/icon_menu.png'),
    icon_edit: require('../../assets/images/icon_edit.png'),    
    ico_circle_plus: require('../../assets/images/ico_circle_plus.png'),
    current_loc_pin: require('../../assets/images/current_loc_pin.png'),
    pin_user: require('../../assets/images/pin_user.png'),
    pin_profile: require('../../assets/images/pin_profile.png'),

    placeholder_image: require('../../assets/images/placeholder_image.png'),
    map_pin: require('../../assets/images/map_pin.png'),

    ico_list: require('../../assets/images/ico_list.png'),
    icon_close_circle: require('../../assets/images/icon_close_circle.png'),
};

export default Images;
